### ISSUE TITLE
huggingFace账号信息填的并不是token？

### ISSUE THREAD

**Issue by master006** [Datayoo/HuggingFists#1]
![image](https://github.com/Datayoo/HuggingFists/assets/25217361/fd3bee9c-2419-49ed-8a91-be217726bc96)

**Comment by Datayoo** [comment]
请按下面地址下载算子修复包：https://github.com/Datayoo/Operators/blob/main/moo/moo-huggingface-descriptor.zip ，在HuggingFists的资源库-》算子库中上传这个包修复这个问题

**Comment by master006** [comment]
上传成功好像还是不行
![image](https://github.com/Datayoo/HuggingFists/assets/25217361/516e5175-66a9-4ec5-8248-cafa969f6197)

**Comment by Datayoo** [comment]
我们重新更新了下刚才的算子包，加了一个临时的HuggingFace2账号模板，你用这个模板创建账号试试吧

**Comment by master006** [comment]
> 我们重新更新了下刚才的算子包，加了一个临时的HuggingFace2账号模板，你用这个模板创建账号试试吧

项目很赞，随着用的人增多，可能会发现很多不完善的地方，建个微信交流群吧

**Comment by Datayoo** [comment]
谢谢你的宝贵意见。我们在readme里加入了交流群的二维码，欢迎扫码加入
