### ISSUE TITLE
windows环境下安装部署，install.bat文件在哪里呀

### ISSUE THREAD

**Issue by xiaoxi8193** [Datayoo/HuggingFists#9]

**Comment by ShadowOfNan** [comment]
下载的安装包，选中全部解压后的结构应该是如图片所示

![1](https://github.com/Datayoo/HuggingFists/assets/45776402/cd47483b-a86c-4cb4-926e-7771c7c03a25)

**Comment by xiaoxi8193** [comment]
我看到分享的文件不存在了，您能重新分享一下吗？万分感谢

**Comment by xiaoxi8193** [comment]
> 下载的安装包，选中全部解压后的结构应该是如图片所示
> 
> ![1](https://private-user-images.githubusercontent.com/45776402/335916606-cd47483b-a86c-4cb4-926e-7771c7c03a25.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTczODE3MzAsIm5iZiI6MTcxNzM4MTQzMCwicGF0aCI6Ii80NTc3NjQwMi8zMzU5MTY2MDYtY2Q0NzQ4M2ItYTg2Yy00Y2I0LTkyNmUtNzc3MWM3YzAzYTI1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MDMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjAzVDAyMjM1MFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTYyYWZlYzBkYjRlZWIxNWY3NWQ3OWQyZTAzMTE5MWRhMjUyNTg1YjBkNTMzMGU5YTBiNTk2MTJhNjg2NDY1M2YmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.aQnfmxOks8dpLqlepp-nC_aI8p3wNCG6QJNypGJnDNI)

<img width="681" alt="屏幕截图 2024-06-03 102332" src="https://github.com/Datayoo/HuggingFists/assets/87403194/aab72806-c889-43ae-9523-7767e8eeff73">

**Comment by ShadowOfNan** [comment]
【Linux版】
微云：https://share.weiyun.com/xN1xtP58
Github：https://github.com/Datayoo/HuggingFists
百度网盘：链接：https://pan.baidu.com/s/1w93ID1brW-NE0kWgbczIGg?pwd=2024 


【windows版】
微云：https://share.weiyun.com/BcTTAnVr
Github: https://github.com/Datayoo/HuggingFists4Win/tree/main
百度网盘：链接：https://pan.baidu.com/s/1Ke_ReJTiABetQyz-NoXgEg?pwd=2024 


【Mac版】
百度网盘： https://pan.baidu.com/s/12WxZ-2GgMtbQeP7AcmsyHg?pwd=2024
github:
https://github.com/Datayoo/HuggingFists4Mac
【补充算子】
GitHub: https://github.com/Datayoo/Operators
百度网盘：https://pan.baidu.com/s/1iqX0f8xzCXMWVDA7eaqH6Q?pwd=2024
